# Generated by Django 3.2.7 on 2022-07-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nallamapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='user_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
