# Generated by Django 3.2.7 on 2022-07-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nallamapp', '0002_tbl_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='', upload_to='pic/')),
                ('name', models.CharField(default='', max_length=100)),
                ('qty', models.CharField(default='', max_length=100)),
                ('price', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
