# Generated by Django 3.2.7 on 2022-07-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nallamapp', '0003_tbl_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_product',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
