# Generated by Django 3.2.7 on 2022-07-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nallamapp', '0004_tbl_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_product',
            name='discription',
            field=models.CharField(default='', max_length=100),
        ),
    ]
