# Generated by Django 3.2.7 on 2022-07-21 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nallamapp', '0006_tbl_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=100)),
                ('sub', models.CharField(default='', max_length=100)),
                ('complaint', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('reply', models.CharField(default='', max_length=100)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nallamapp.tbl_user')),
            ],
        ),
    ]
