# Generated by Django 3.2.7 on 2022-07-27 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nallamapp', '0008_tbl_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(default='', max_length=30)),
                ('total', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='0', max_length=10)),
                ('product_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='nallamapp.tbl_product')),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='nallamapp.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='order_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(default='', max_length=30)),
                ('payment', models.CharField(default='', max_length=30)),
                ('date', models.CharField(default='', max_length=100)),
                ('time', models.CharField(default='', max_length=100)),
                ('total', models.CharField(default='', max_length=30)),
                ('payment_status', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='', max_length=30)),
                ('cart_id', models.CharField(default='', max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nallamapp.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='order_item_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(default='', max_length=30)),
                ('date', models.CharField(default='', max_length=100)),
                ('time', models.CharField(default='', max_length=100)),
                ('payment_status', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='', max_length=30)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nallamapp.tbl_cart')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nallamapp.order_tb')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nallamapp.tbl_product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nallamapp.tbl_user')),
            ],
        ),
    ]
