# Generated by Django 3.2.7 on 2022-07-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nallamapp', '0009_order_item_tb_order_tb_tbl_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_product',
            name='reply',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tbl_product',
            name='reviews',
            field=models.CharField(default='', max_length=100),
        ),
    ]
