# Generated by Django 3.2.7 on 2022-07-29 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nallamapp', '0010_auto_20220729_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_product',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='tbl_product',
            name='reviews',
        ),
        migrations.CreateModel(
            name='Tbl_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(default='', max_length=100)),
                ('reply', models.CharField(default='', max_length=100)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nallamapp.tbl_product')),
            ],
        ),
    ]
