# Generated by Django 3.2.7 on 2022-07-29 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nallamapp', '0011_auto_20220729_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_review',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nallamapp.tbl_user'),
        ),
    ]
