# Generated by Django 3.2.7 on 2022-07-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nallamapp', '0012_tbl_review_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_review',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
