# Generated by Django 3.2.5 on 2022-10-24 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nallamapp', '0013_tbl_review_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tbl_Report',
        ),
    ]
