# Generated by Django 3.2.5 on 2022-10-24 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nallamapp', '0014_delete_tbl_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_item_tb',
            old_name='status',
            new_name='packing_status',
        ),
    ]
