# Generated by Django 3.2.5 on 2022-10-24 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nallamapp', '0015_rename_status_order_item_tb_packing_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=100)),
                ('total_amt', models.CharField(default='', max_length=100)),
                ('card_name', models.CharField(default='', max_length=100)),
                ('card_number', models.CharField(default='', max_length=100)),
                ('card_cvv', models.CharField(default='', max_length=100)),
                ('card_expdate', models.CharField(default='', max_length=100)),
                ('pay_status', models.CharField(default='', max_length=100)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nallamapp.order_tb')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nallamapp.tbl_product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nallamapp.tbl_user')),
            ],
        ),
    ]
