# Generated by Django 3.2.5 on 2022-10-25 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nallamapp', '0016_tb_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tbl_Feedback',
        ),
    ]
