# Generated by Django 5.1.7 on 2025-07-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nallamapp', '0017_delete_tbl_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_review',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
